### ISSUE TITLE
Demo does not present warnings or errors but Jaeger UI output is not as expected

### ISSUE THREAD

**Issue by simonhf** [albertteoh/jaeger-go-example#1] opened 2021-08-09 23:01 UTC
Followed through the instructions and everything appeared to work as expected on the command line:

```
$ git clone https://github.com/albertteoh/jaeger-go-example.git

$ cd jaeger-go-example

$ make start
[+] Building 46.6s (14/14) FINISHED      
...
[+] Building 24.6s (14/14) FINISHED 
...
Creating network "jaeger-go-example_default" with the default driver
Creating jaeger                        ... done
Creating jaeger-go-example_service-a_1 ... done
Creating jaeger-go-example_service-b_1 ... done

$ curl -w '\n' http://localhost:8081/ping
service-a -> service-b
```

Can also access Jaeger UI [2] BUT...
* Instead of seeing a Service called `service-a` there is only `jaeger-query`, and
* Upon selecting service `jaeger-query` and hitting `Find Traces`, instead of seeing a single trace with multiple spans, there are multiple traces with a single span:

![image](https://user-images.githubusercontent.com/357158/128784672-05d2f8ae-2003-46bf-8270-08fdfc5c2657.png)

Looking inside a trace looks like this:

![image](https://user-images.githubusercontent.com/357158/128784772-30a2284b-6379-4148-8418-90d713367da0.png)

Why isn't the demo working and how to fix it?

[1] https://logz.io/blog/go-instrumentation-distributed-tracing-jaeger/
[2]  http://localhost:16686/search
[3] https://dytvr9ot2sszz.cloudfront.net/wp-content/uploads/2020/12/search-results-1024x467.png

**Comment by simonhf** [comment] 2021-08-09 23:15
In case it helps, here are the logs from the `service-a` and `service-b` containers...:

```
$ make stop ; make start ; curl -w '\n' http://localhost:8081/ping ; echo "docker logs service-a:" ; docker logs `docker ps -aqf "name=service-a"` ; echo "docker logs service-b:" ; docker logs `docker ps -aqf "name=service-b"`
...
service-a -> service-b
docker logs service-a:
2021/08/10 00:41:42 debug logging disabled
2021/08/10 00:41:42 Initializing logging reporter
2021/08/10 00:41:42 debug logging disabled
2021/08/10 00:41:42 Listening on localhost:8081
2021/08/10 00:41:50 http.HandleFunc(/ping) // r=&{Method:GET URL:/ping Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept:[*/*] User-Agent:[curl/7.64.1]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:localhost:8081 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.32.1:61964 RequestURI:/ping TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc000108800}
2021/08/10 00:41:50 StartSpanFromRequest() // spanCtx=<nil>
2021/08/10 00:41:50 StartSpanFromRequest() // span=6fbd37b93bc2c03d:6fbd37b93bc2c03d:0000000000000000:1
2021/08/10 00:41:50 xhttp.Do()
2021/08/10 00:41:52 xhttp.Do() // status=200 body=service-b
2021/08/10 00:41:52 Reporting span 6fbd37b93bc2c03d:58b37716304bfb63:6fbd37b93bc2c03d:1
2021/08/10 00:41:52 http.HandleFunc(/ping) // .Write()
2021/08/10 00:41:52 Reporting span 6fbd37b93bc2c03d:6fbd37b93bc2c03d:0000000000000000:1
docker logs service-b:
2021/08/10 00:41:44 debug logging disabled
2021/08/10 00:41:44 Initializing logging reporter
2021/08/10 00:41:44 debug logging disabled
2021/08/10 00:41:44 Listening on localhost:8082
2021/08/10 00:41:50 http.HandleFunc(/ping) // r=&{Method:GET URL:/ping Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Accept-Encoding:[gzip] Uber-Trace-Id:[6fbd37b93bc2c03d:58b37716304bfb63:6fbd37b93bc2c03d:1] User-Agent:[Go-http-client/1.1]] Body:{} GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:service-b:8082 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr:192.168.32.2:55388 RequestURI:/ping TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc0000a0140}
2021/08/10 00:41:50 StartSpanFromRequest() // spanCtx=6fbd37b93bc2c03d:58b37716304bfb63:6fbd37b93bc2c03d:1
2021/08/10 00:41:50 StartSpanFromRequest() // span=6fbd37b93bc2c03d:2c03d3f29937736f:58b37716304bfb63:1
2021/08/10 00:41:50 http.HandleFunc(/ping) // span=6fbd37b93bc2c03d:2c03d3f29937736f:58b37716304bfb63:1
2021/08/10 00:41:52 http.HandleFunc(/ping) // .Write()
2021/08/10 00:41:52 Reporting span 6fbd37b93bc2c03d:2c03d3f29937736f:58b37716304bfb63:1
```

...after adding a little instrumentation:

```
$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index bead1e6..3f45007 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,16 +6,23 @@ services:
       - "8081:8081"
     environment:
       - OUTBOUND_HOST_PORT=service-b:8082
+      - JAEGER_REPORTER_LOG_SPANS=true
   service-b:
     image: service-b
     ports:
       - "8082:8082"
   localhost:
-    image: jaegertracing/all-in-one
+    image: jaegertracing/all-in-one:latest
+    command: --log-level=debug
     container_name: jaeger
     ports:
+      - "5775:5775/udp"
       - "6831:6831/udp"
       - "6832:6832/udp"
+      - "5778:5778"
+      - "16685:16685"
       - "16686:16686"
       - "14268:14268"
+      - "14269:14269"
       - "14250:14250"
+      - "9411:9411"
diff --git a/lib/http/client.go b/lib/http/client.go
index 78c476b..837a2f1 100644
--- a/lib/http/client.go
+++ b/lib/http/client.go
@@ -2,6 +2,7 @@ package xhttp
 
 import (
        "fmt"
+       "log"
        "io/ioutil"
        "net/http"
 )
@@ -9,6 +10,7 @@ import (
 // Do executes an HTTP request and returns the response body as a string.
 // Non-200 response codes will be returned as an error with the response body.
 func Do(req *http.Request) (string, error) {
+       log.Printf("xhttp.Do()")
        resp, err := http.DefaultClient.Do(req)
        if err != nil {
                return "", err
@@ -20,6 +22,7 @@ func Do(req *http.Request) (string, error) {
                return "", err
        }
 
+       log.Printf("xhttp.Do() // status=%d body=%+v", resp.StatusCode, string(body))
        if resp.StatusCode != 200 {
                return "", fmt.Errorf("StatusCode: %d, Body: %s", resp.StatusCode, body)
        }
diff --git a/lib/tracing/span.go b/lib/tracing/span.go
index 6d5fb0f..6b7c8b3 100644
--- a/lib/tracing/span.go
+++ b/lib/tracing/span.go
@@ -1,6 +1,7 @@
 package tracing
 
 import (
+       "log"
        "net/http"
 
        "github.com/opentracing/opentracing-go"
@@ -11,5 +12,8 @@ import (
 // and starts a new child span if there is a parent span.
 func StartSpanFromRequest(tracer opentracing.Tracer, r *http.Request) opentracing.Span {
        spanCtx, _ := Extract(tracer, r)
-       return tracer.StartSpan("ping-receive", ext.RPCServerOption(spanCtx))
+       log.Printf("StartSpanFromRequest() // spanCtx=%+v", spanCtx)
+       span := tracer.StartSpan("ping-receive", ext.RPCServerOption(spanCtx))
+       log.Printf("StartSpanFromRequest() // span=%+v", span)
+       return span
 }
diff --git a/service-a/service-a.go b/service-a/service-a.go
index cbfa95f..1593816 100644
--- a/service-a/service-a.go
+++ b/service-a/service-a.go
@@ -26,6 +26,7 @@ func main() {
        }
 
        http.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) {
+               log.Printf("http.HandleFunc(/ping) // r=%+v", r)
                span := tracing.StartSpanFromRequest(tracer, r)
                defer span.Finish()
 
@@ -34,6 +35,7 @@ func main() {
                if err != nil {
                        log.Fatalf("Error occurred: %s", err)
                }
+               log.Printf("http.HandleFunc(/ping) // .Write()")
                w.Write([]byte(fmt.Sprintf("%s -> %s", thisServiceName, response)))
        })
        log.Printf("Listening on localhost:8081")
diff --git a/service-b/service-b.go b/service-b/service-b.go
index cb9bae3..e2f9df7 100644
--- a/service-b/service-b.go
+++ b/service-b/service-b.go
@@ -4,6 +4,7 @@ import (
        "fmt"
        "log"
        "net/http"
+       "time"
 
        "ping/lib/tracing"
 
@@ -18,9 +19,14 @@ func main() {
        opentracing.SetGlobalTracer(tracer)
 
        http.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) {
+               log.Printf("http.HandleFunc(/ping) // r=%+v", r)
                span := tracing.StartSpanFromRequest(tracer, r)
+               log.Printf("http.HandleFunc(/ping) // span=%+v", span)
                defer span.Finish()
 
+               time.Sleep(2 * time.Second)
+
+               log.Printf("http.HandleFunc(/ping) // .Write()")
                w.Write([]byte(fmt.Sprintf("%s", thisServiceName)))
        })
        log.Printf("Listening on localhost:8082")
```

I also noticed that even though I added in a 2 second delay in 'service-b' -- in addition to the issues above -- none of the traces captured appear to reflect the delay. Any ideas why?

**Comment by simonhf** [comment] 2021-08-10 01:56
Small bit of progress :-) I figured out that `jaeger-query` in the UI is there because the Jaeger UI monitors itself. So if `service-a` is not in the Service drop-down box, that probably means that the queries are not getting through to the agent? Trying to figure out why...

**Comment by simonhf** [comment] 2021-08-10 04:39
Also, tried pushing a span directly using curl:

```
$ curl -vvv -X POST http://localhost:9411 -H 'Content-Type: application/json' -d '[{
 "id": "1234",
 "traceId": "0123456789abcdef",
 "timestamp": 1608239395286533,
 "duration": 100000,
 "name": "span from bash!",
 "tags": {
    "http.method": "GET",
    "http.path": "/api"
  },
  "localEndpoint": {
    "serviceName": "shell script"
  }
}]'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9411 (#0)
> POST / HTTP/1.1
> Host: localhost:9411
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 258
> 
* upload completely sent off: 258 out of 258 bytes
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection 0
```

But `Service` drop-down at http://localhost:16686/search still does not change :-(

Is "Empty reply from server" correct? Jaeger does appear to be listening on the port:

```
$ sudo netstat -an | egrep 9411
tcp46      0      0  *.9411                 *.*                    LISTEN
```

These are the log entries for Jaeger:

```
$ docker logs 453a4685c897                                                          
2021/08/10 04:30:43 maxprocs: Leaving GOMAXPROCS=4: CPU quota undefined
{"level":"info","ts":1628569843.3402455,"caller":"flags/service.go:117","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1628569843.3404548,"caller":"flags/service.go:123","msg":"Mounting expvar handler on admin server","route":"/debug/vars"}
{"level":"info","ts":1628569843.3411887,"caller":"flags/admin.go:105","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1628569843.3413167,"caller":"flags/admin.go:111","msg":"Starting admin HTTP server","http-addr":":14269"}
{"level":"info","ts":1628569843.3416636,"caller":"flags/admin.go:97","msg":"Admin server started","http.host-port":"[::]:14269","health-status":"unavailable"}
{"level":"info","ts":1628569843.3455226,"caller":"memory/factory.go:61","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1628569843.3463867,"caller":"static/strategy_store.go:201","msg":"No sampling strategies provided or URL is unavailable, using defaults"}
{"level":"info","ts":1628569843.3551927,"caller":"server/grpc.go:76","msg":"Starting jaeger-collector gRPC server","grpc.host-port":":14250"}
{"level":"info","ts":1628569843.355334,"caller":"server/http.go:47","msg":"Starting jaeger-collector HTTP server","http host-port":":14268"}
{"level":"info","ts":1628569843.355785,"caller":"server/zipkin.go:48","msg":"Not listening for Zipkin HTTP traffic, port not configured"}
{"level":"info","ts":1628569843.355922,"caller":"grpc/builder.go:70","msg":"Agent requested insecure grpc connection to collector(s)"}
{"level":"info","ts":1628569843.35601,"caller":"grpc@v1.29.1/clientconn.go:243","msg":"parsed scheme: \"\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3561945,"caller":"grpc@v1.29.1/clientconn.go:249","msg":"scheme \"\" not registered, fallback to default scheme","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3562765,"caller":"grpc@v1.29.1/resolver_conn_wrapper.go:143","msg":"ccResolverWrapper: sending update to cc: {[{:14250  <nil> 0 <nil>}] <nil> <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3563173,"caller":"grpc@v1.29.1/clientconn.go:667","msg":"ClientConn switching balancer to \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3563275,"caller":"grpc@v1.29.1/clientconn.go:682","msg":"Channel switches to new LB policy \"round_robin\"","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3564358,"caller":"grpc@v1.29.1/balancer_conn_wrappers.go:127","msg":"base.baseBalancer: got new ClientConn state: {{[{:14250  <nil> 0 <nil>}] <nil> <nil>} <nil>}","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3564928,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3566597,"caller":"grpc@v1.29.1/balancer_conn_wrappers.go:78","msg":"base.baseBalancer: handle SubConn state change: 0xc00057b020, CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3567355,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to CONNECTING","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3566685,"caller":"grpc@v1.29.1/clientconn.go:1193","msg":"Subchannel picks a new address \":14250\" to connect","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.356795,"caller":"grpc/builder.go:108","msg":"Checking connection to collector"}
{"level":"info","ts":1628569843.3576741,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"CONNECTING"}
{"level":"info","ts":1628569843.3580222,"caller":"command-line-arguments/main.go:218","msg":"Starting agent"}
{"level":"info","ts":1628569843.3581836,"caller":"querysvc/query_service.go:137","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1628569843.358238,"caller":"app/flags.go:128","msg":"Archive storage not initialized"}
{"level":"info","ts":1628569843.3583214,"caller":"app/agent.go:69","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1628569843.3614678,"caller":"app/static_handler.go:181","msg":"UI config path not provided, config file will not be watched"}
{"level":"info","ts":1628569843.361964,"caller":"app/server.go:170","msg":"Query server started"}
{"level":"info","ts":1628569843.3622153,"caller":"app/server.go:249","msg":"Starting GRPC server","port":16685,"addr":":16685"}
{"level":"info","ts":1628569843.362326,"caller":"app/server.go:230","msg":"Starting HTTP server","port":16686,"addr":":16686"}
{"level":"info","ts":1628569843.3620985,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1628569843.362415,"caller":"grpc@v1.29.1/clientconn.go:1056","msg":"Subchannel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3625007,"caller":"grpc@v1.29.1/balancer_conn_wrappers.go:78","msg":"base.baseBalancer: handle SubConn state change: 0xc00057b020, READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3625844,"caller":"base/balancer.go:200","msg":"roundrobinPicker: newPicker called with info: {map[0xc00057b020:{{:14250  <nil> 0 <nil>}}]}","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.3626564,"caller":"grpc@v1.29.1/clientconn.go:417","msg":"Channel Connectivity change to READY","system":"grpc","grpc_log":true}
{"level":"info","ts":1628569843.362677,"caller":"grpc/builder.go:119","msg":"Agent collector connection state change","dialTarget":":14250","status":"READY"}
{"level":"debug","ts":1628569876.3480296,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":649}
{"level":"debug","ts":1628569876.3481824,"caller":"reporter/client_metrics.go:177","msg":"received batch from a new client, starting to keep stats","client-uuid":"7028adaa3f3328d4"}
{"level":"debug","ts":1628569876.3492713,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"6d65ce6e7331d436","span-id":"6d65ce6e7331d436"}
{"level":"debug","ts":1628569876.3492901,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"7482d5287a5e8197","span-id":"7482d5287a5e8197"}
{"level":"debug","ts":1628569881.3441682,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":645}
{"level":"debug","ts":1628569881.3448696,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"1db7bc02e25747b7","span-id":"1db7bc02e25747b7"}
{"level":"debug","ts":1628569881.3449798,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"1cf5c05311904969","span-id":"1cf5c05311904969"}
{"level":"debug","ts":1628570091.3445823,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":645}
{"level":"debug","ts":1628570091.346692,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"3c1c265efd655753","span-id":"3c1c265efd655753"}
{"level":"debug","ts":1628570091.3466494,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"2b33949ad3240ff4","span-id":"2b33949ad3240ff4"}
{"level":"debug","ts":1628570095.3435433,"caller":"processors/thrift_processor.go:120","msg":"Span(s) received by the agent","bytes-received":646}
{"level":"debug","ts":1628570095.3441691,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"1ab3de238a05c87b","span-id":"1ab3de238a05c87b"}
{"level":"debug","ts":1628570095.3445468,"caller":"app/span_processor.go:149","msg":"Span written to the storage by the collector","trace-id":"208cdf1baf7f61c7","span-id":"208cdf1baf7f61c7"}
```

Those last debug entries occur when I access http://localhost:16686/search and look for a new `Service` in the drop-down.

If I add this to the Jaeger docker-compose section:

```
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
```

Then the Jaeger log changes to:

```
...
{"level":"info","ts":1628571631.365469,"caller":"server/zipkin.go:52","msg":"Listening for Zipkin HTTP traffic","zipkin host-port":":9411"}
...
```

But now the curl request results in "404 page not found" ?!

```
curl -vvv -X POST http://localhost:9411 -H 'Content-Type: application/json' -d '[{
 "id": "1234",
 "traceId": "0123456789abcdef",
 "timestamp": 1608239395286533,
 "duration": 100000,
 "name": "span from bash!",
 "tags": {
    "http.method": "GET",
    "http.path": "/api"
  },
  "localEndpoint": {
    "serviceName": "shell script"
  }
}]'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9411 (#0)
> POST / HTTP/1.1
> Host: localhost:9411
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 258
> 
* upload completely sent off: 258 out of 258 bytes
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Vary: Origin
< X-Content-Type-Options: nosniff
< Date: Tue, 10 Aug 2021 05:03:47 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host localhost left intact
* Closing connection 0
```

[1] https://grafana.com/docs/tempo/latest/api_docs/pushing-spans-with-http/?pg=docs

**Comment by albertteoh** [comment] 2021-08-10 11:55
Thanks for reporting this bug @simonhf and providing all the details, and can reproduce the problem.

If I run the services locally outside of docker containers, it works fine, so it looks like a docker networking issue, and may perhaps be related to docker-compose versions. I'll look into it and keep you posted.

**Comment by albertteoh** [comment] 2021-08-11 13:36
@simonhf this should be [fixed](https://github.com/albertteoh/jaeger-go-example/commit/30535721088bf79b099d84edbae219cfc78afe2b) can you please try again (`git pull && make start`)?

**Comment by albertteoh** [comment] 2021-08-14 20:04
Closing as the issue has been addressed, feel free to reopen if you believe otherwise.

**Closed as completed by albertteoh** 2021-08-14 20:04 UTC
Labels: bug
